import Head from 'next/head'
import Image from 'next/image'
import { Poppins } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { BsEyeFill, BsPerson } from "react-icons/bs"
import Card from '@/partials/card'

const inter = Poppins({ subsets: ['latin'], weight: '700' })

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>ARGUS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.logo} >
          <BsEyeFill size={64} />
          <h1>ARGUS</h1>
        </div>

        <div className={styles.info}>
          <div className={styles.menu}>
            <button>HEEE</button>
            <button>HEEE</button>
            <button>HEEE</button>
            <button>HEEE</button>
            <button>HEEE</button>
          </div>
          <div className={styles.user}>
            <BsPerson size={64} />
          </div>
        </div>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        {/* Mein Campaigns */}
        <div className={styles.drawer} id='owned'>
          <h1 className={styles.title} >Your campaigns</h1>
          <div className={styles.cards}>
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
          </div>
        </div>

        {/* Mein Supported Campaigns */}
        <div className={styles.drawer} id='supported'>
          <h1 className={styles.title} >Campaigns you support</h1>
          <Card />
        </div>
        {/* Featured Campaigns */}
        <div className={styles.drawer} id="featured">
          <h1 className={styles.title}>Campaigns We Stain</h1>
        </div>

        {/*  */}
      </main>
      <footer>

      </footer>
    </div>
  )
}
