import Head from 'next/head'
import Image from 'next/image'
import { Oswald } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { BsEyeFill, BsPerson } from "react-icons/bs"
import Card from '@/partials/card'
import Link from 'next/link'

const inter = Oswald({ subsets: ['latin'], weight: '700' })

export default function Home() {
  return (
    <div className={inter.className}>
      <Head>
        <title>ARGUS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Link className={styles.logo} href='/' >
          <BsEyeFill size={64} />
          <h1>ARGUS</h1>
        </Link>

        <div className={styles.info}>
          <div className={styles.menu}>
            <Link href='/' className={styles.button} >WASD</Link>
            <button className={styles.button} >DSAW</button>
            <button className={styles.button} >WASD</button>
            <button className={styles.button} >DSAW</button>
            <button className={styles.button} >WASD</button>
          </div>
          <Link href='/api/hello' className={styles.user}>
            <BsPerson size={64} />
          </Link>
        </div>
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        {/* About Us */}
        <div className={styles.about} >

        </div>

        {/* Mein Supported Campaigns */}
        <div className={styles.drawer} id='supported'>
          <h1 className={styles.title} >Featured campaigns</h1>
          <div className={styles.cards}>
            <Card title="Heey" description="HEEY" />
            <Card title="Heey" />
            <Card title="Heey" description="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt, totam?" />
            <Card title="Heey" />
            <Card title="Heey" />
            <Card title="Heey" />
            <Card title="Heey" />
            <Card title="Heey" />
            <Card title="Heey" />
            <Card title="Heey" />
          </div>
        </div>

        {/* Contact Form */}
      </main>
      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
